
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 inside the container
    restart: always
    volumes:
      - ./front-end:/app # Bind mount for development
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000" # Expose backend API on port 5000
    restart: always
    volumes:
      - ./back-end:/app # Useful for development (hot-reload)
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://wassim:0000@nodeexpress.mr7l440.mongodb.net/cruddevops?retryWrites=true&w=majority&appName=nodeexpress

  mongodb:
    image: mongo:5 # Official MongoDB image
    container_name: mongo-db
    ports:
      - "27017:27017" # Map MongoDB's default port
    restart: always
    volumes:
      - mongodb_data:/data/db # Persist data across container restarts

volumes:
  mongodb_data:
