stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  MONGO_URI: "mongodb+srv://wassim:0000@nodeexpress.mr7l440.mongodb.net/cruddevops?retryWrites=true&w=majority&appName=nodeexpress"
  PORT: 5000

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker build -t mern-backend ./back-end
    - docker build -t react-frontend ./front-end

test:
  stage: test
  image: node:18
  script:
    # Backend Tests
    - cd back-end
    - npm install
    - npm test
    # Frontend Tests
    - cd ../front-end
    - npm install
    - npm test
  allow_failure: true

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker tag mern-backend $CI_REGISTRY_IMAGE/backend:latest
    - docker tag react-frontend $CI_REGISTRY_IMAGE/frontend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
